{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "markdow.fullname" . }}
  labels:
    {{- include "markdow.labels" . | nindent 4 }}
  {{- $defaults := dict }}
  {{- if .Values.ingress.proxyBodySize }}
  {{- $_ := set $defaults "nginx.ingress.kubernetes.io/proxy-body-size" .Values.ingress.proxyBodySize }}
  {{- end }}
  {{- with merge (deepCopy (.Values.ingress.annotations | default dict)) $defaults }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "markdow.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
  tls:
    - secretName: {{ .Values.ingress.tlsSecretName }}
      hosts:
        - {{ .Values.host | quote }}
{{- end }}
